const moment = require('moment');

// Exact PDF Styles to Match Official Reports
const styles = `
    <style>
        body { font-family: 'Times New Roman', serif; font-size: 11px; color: #000; padding: 20px; }
        
        .header-container { text-align: center; margin-bottom: 5px; }
        .hospital-name { font-size: 26px; font-weight: bold; text-transform: uppercase; margin-bottom: 2px; }
        .address-line { font-size: 11px; margin-bottom: 1px; }
        
        .divider { border-bottom: 2px solid #000; margin: 5px 0 15px 0; }
        .report-heading { text-align: center; font-size: 16px; font-weight: bold; text-decoration: underline; margin-bottom: 15px; text-transform: uppercase; }
        
        .report-meta { width: 100%; margin-bottom: 10px; font-size: 12px; }
        .meta-row { display: flex; justify-content: space-between; margin-bottom: 5px; }
        .meta-left { text-align: left; }
        .meta-right { text-align: right; }

        table { width: 100%; border-collapse: collapse; border: 1px solid #000; margin-top: 5px; }
        th { background-color: #eee; border: 1px solid #000; padding: 5px; text-align: center; font-weight: bold; font-size: 11px; text-transform: uppercase; }
        td { border: 1px solid #000; padding: 5px; font-size: 11px; vertical-align: top; }
        
        .text-right { text-align: right; }
        .text-center { text-align: center; }
        .text-left { text-align: left; }
        .bold { font-weight: bold; }

        .footer { margin-top: 30px; display: flex; justify-content: flex-end; padding-top: 40px; }
        .signature { text-align: center; border-top: 1px solid #000; width: 150px; padding-top: 5px; font-weight: bold; }
        
        .page-footer { position: fixed; bottom: 0; left: 0; right: 0; font-size: 10px; text-align: center; border-top: 1px solid #ccc; padding-top: 2px; }
    </style>
`;

const getHeader = () => `
    <div class="header-container">
        <div class="hospital-name">CITY HOSPITAL</div>
        <div class="address-line">123, Health Avenue, Medical District, Mumbai - 400001</div>
        <div class="address-line">Phone: +91 98765 43210 | Email: info@cityhospital.com</div>
        <div class="divider"></div>
    </div>
`;

const getFooter = () => `
    <div class="page-footer">
        Generated By: System Admin | Date: ${moment().format('DD/MM/YYYY hh:mm A')}
    </div>
`;

// Pharmacy Billing Report
// Columns: Bill No, Bill Date, Patient Name, Doctor Name, Pay Mode, Amount
exports.pharmacyBilling = (data) => `
    <!DOCTYPE html>
    <html>
    <head>${styles}</head>
    <body>
        ${getHeader()}
        <div class="report-heading">Pharmacy Sales Report - Daily</div>
        
        <div class="report-meta">
            <div class="meta-row">
                <div class="meta-left"><strong>Report Period:</strong> ${data.date ? moment(data.date).format('DD-MMM-YYYY') : 'All'}</div>
                <div class="meta-right"><strong>Total Records:</strong> ${data.items.length}</div>
            </div>
        </div>

        <table>
            <thead>
                <tr>
                    <th width="5%">S.No</th>
                    <th width="10%">Bill No</th>
                    <th width="12%">Date</th>
                    <th width="25%">Patient Name</th>
                    <th width="20%">Doctor</th>
                    <th width="10%">Mode</th>
                    <th width="15%" class="text-right">Net Amount</th>
                </tr>
            </thead>
            <tbody>
                ${data.items.map((item, i) => `
                    <tr>
                        <td class="text-center">${i + 1}</td>
                        <td class="text-center">${item.billNo}</td>
                        <td class="text-center">${item.date}</td>
                        <td>${item.patientName}</td>
                        <td>${item.doctor}</td>
                        <td class="text-center">${item.paymentMode || 'CASH'}</td>
                        <td class="text-right">${item.amount}</td>
                    </tr>
                `).join('')}
                <tr>
                    <td colspan="6" class="text-right bold">Grand Total:</td>
                    <td class="text-right bold">${data.totalRevenue}</td>
                </tr>
            </tbody>
        </table>

        <div class="footer">
            <div class="signature">Authorized Signature</div>
        </div>
        ${getFooter()}
    </body>
    </html>
`;

// Pharmacy Purchase Report
// Columns: Inv No, Date, Supplier Name, Item Details, Payment Mode, Total Amount
exports.pharmacyPurchase = (data) => `
    <!DOCTYPE html>
    <html>
    <head>${styles}</head>
    <body>
        ${getHeader()}
        <div class="report-heading">Pharmacy Purchase Register</div>
        
        <table>
            <thead>
                <tr>
                    <th width="5%">S.No</th>
                    <th width="10%">Inv No</th>
                    <th width="10%">Date</th>
                    <th width="30%">Supplier Name</th>
                    <th width="10%" class="text-center">Items</th>
                    <th width="15%" class="text-right">Total Amount</th>
                </tr>
            </thead>
            <tbody>
                ${data.items.map((item, i) => `
                    <tr>
                        <td class="text-center">${i + 1}</td>
                        <td class="text-center">${item.invoiceNo}</td>
                        <td class="text-center">${item.date}</td>
                        <td>${item.supplier}</td>
                        <td class="text-center">${item.itemCount}</td>
                        <td class="text-right">${item.total}</td>
                    </tr>
                `).join('')}
                <tr>
                    <td colspan="5" class="text-right bold">Total Purchase Value:</td>
                    <td class="text-right bold">${data.totalPurchase}</td>
                </tr>
            </tbody>
        </table>
        
        <div class="footer">
            <div class="signature">Store Manager</div>
        </div>
        ${getFooter()}
    </body>
    </html>
`;

// Pharmacy Stock Report
// Columns: Product ID, Product Name, Batch No, Expiry, Rack, Stock, MRP, Total Value
exports.pharmacyStock = (data) => `
    <!DOCTYPE html>
    <html>
    <head>${styles}</head>
    <body>
        ${getHeader()}
        <div class="report-heading">Pharmacy Stock Statement</div>
        
        <table>
            <thead>
                <tr>
                    <th width="5%">S.No</th>
                    <th width="10%">Code</th>
                    <th width="25%">Product Name</th>
                    <th width="10%">Batch</th>
                    <th width="10%">Expiry</th>
                    <th width="10%" class="text-right">Qty</th>
                    <th width="10%" class="text-right">MRP</th>
                    <th width="15%" class="text-right">Total Value</th>
                </tr>
            </thead>
            <tbody>
                ${data.items.map((item, i) => `
                    <tr>
                        <td class="text-center">${i + 1}</td>
                        <td class="text-center">${item.code}</td>
                        <td>${item.name}</td>
                        <td class="text-center">${item.batch}</td>
                        <td class="text-center">${item.expiry}</td>
                        <td class="text-right">${item.qty}</td>
                        <td class="text-right">${item.mrp}</td>
                        <td class="text-right">${(item.qty * item.mrp).toFixed(2)}</td>
                    </tr>
                `).join('')}
                <tr>
                    <td colspan="7" class="text-right bold">Total Stock Valuation:</td>
                    <td class="text-right bold">${data.totalValue}</td>
                </tr>
            </tbody>
        </table>
        
        <div class="footer">
            <div class="signature">Pharmacist</div>
        </div>
        ${getFooter()}
    </body>
    </html>
`;

// Pharmacy Return Report
exports.pharmacyReturn = (data) => `
    <!DOCTYPE html>
    <html>
    <head>${styles}</head>
    <body>
        ${getHeader()}
        <div class="report-heading">Pharmacy Return / Expiry Report</div>

        <table>
            <thead>
                <tr>
                    <th width="5%">S.No</th>
                    <th width="25%">Product Name</th>
                    <th width="10%">Batch</th>
                    <th width="10%">Expiry</th>
                    <th width="10%" class="text-center">Qty</th>
                    <th width="20%">Reason</th>
                    <th width="15%" class="text-right">Loss Amount</th>
                </tr>
            </thead>
            <tbody>
                ${data.items.map((item, i) => `
                    <tr>
                        <td class="text-center">${i + 1}</td>
                        <td>${item.medicine}</td>
                        <td class="text-center">${item.batch}</td>
                        <td class="text-center">2024-05-01</td> <!-- Mock expiry if missing -->
                        <td class="text-center">${item.qty}</td>
                        <td>${item.reason}</td>
                        <td class="text-right">${item.value}</td>
                    </tr>
                `).join('')}
                 <tr>
                    <td colspan="6" class="text-right bold">Total Loss Value:</td>
                    <td class="text-right bold">0.00</td> <!-- Todo calc -->
                </tr>
            </tbody>
        </table>
        
        <div class="footer">
            <div class="signature">Authorized Signature</div>
        </div>
        ${getFooter()}
    </body>
    </html>
`;

// OP Patient History (Daily OP Collection)
exports.dailyOp = (data) => `
    <!DOCTYPE html>
    <html>
    <head>${styles}</head>
    <body>
        ${getHeader()}
        <div class="report-heading">Daily OP Collection Report</div>
        
        <div class="report-meta">
            <div class="meta-row">
                <div class="meta-left"><strong>Date:</strong> ${moment(data.date).format('DD-MMM-YYYY')}</div>
            </div>
        </div>

        <table>
            <thead>
                <tr>
                    <th width="8%">Inv No</th>
                    <th width="25%">Patient Name</th>
                    <th width="15%">Mobile</th>
                    <th width="15%">Category</th>
                    <th width="10%">Status</th>
                    <th width="12%" class="text-right">Bill Amt</th>
                    <th width="12%" class="text-right">Paid Amt</th>
                </tr>
            </thead>
            <tbody>
                ${data.items.map((item, i) => `
                    <tr>
                        <td class="text-center">${item.id}</td>
                        <td>${item.patient_name}</td>
                        <td class="text-center">-</td>
                        <td class="text-center">${item.category}</td>
                        <td class="text-center">${item.status}</td>
                        <td class="text-right">${item.total_amount}</td>
                        <td class="text-right">${item.paid_amount}</td>
                    </tr>
                `).join('')}
                <tr>
                    <td colspan="6" class="text-right bold">Net Collection:</td>
                    <td class="text-right bold text-right">${data.totalCollection}</td>
                </tr>
            </tbody>
        </table>

        <div class="footer">
            <div class="signature">Cashier</div>
        </div>
        ${getFooter()}
    </body>
    </html>
`;

exports.opPatientHistory = (data) => `
    <!DOCTYPE html>
    <html>
    <head>${styles}</head>
    <body>
        ${getHeader()}
        <div class="report-heading">Patient Medical History Record</div>
        
        <table style="margin-bottom: 20px; border: none;">
            <tr style="border: none;">
                <td style="border: none; padding: 2px;"><strong>Patient Name:</strong> ${data.patientName}</td>
                <td style="border: none; padding: 2px;"><strong>Patient ID:</strong> ${data.patientId}</td>
            </tr>
            <tr style="border: none;">
                <td style="border: none; padding: 2px;"><strong>Age / Gender:</strong> ${data.age} / ${data.gender}</td>
                <td style="border: none; padding: 2px;"><strong>Contact:</strong> ${data.mobile || 'N/A'}</td>
            </tr>
        </table>

        <table>
            <thead>
                <tr>
                    <th width="12%">Date</th>
                    <th width="20%">Doctor</th>
                    <th width="25%">Diagnosis / Complaints</th>
                    <th width="30%">Prescription / Treatment</th>
                    <th width="13%" class="text-right">Fees</th>
                </tr>
            </thead>
            <tbody>
                 ${data.visits && data.visits.length > 0 ? data.visits.map(v => `
                    <tr>
                        <td>${v.date}</td>
                        <td>${v.doctor}</td>
                        <td>${v.diagnosis}</td>
                        <td>${v.prescription}</td>
                        <td class="text-right">${v.fee}</td>
                    </tr>
                `).join('') : '<tr><td colspan="5" class="text-center">No history record found</td></tr>'}
            </tbody>
        </table>
        
         <div class="footer">
            <div class="signature">Doctor Signature</div>
        </div>
        ${getFooter()}
    </body>
    </html>
`;
