apiVersion: v1
kind: Secret
metadata:
  name: hms-db-secret
  namespace: hms-production
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdA==

---
apiVersion: v1
kind: Secret
metadata:
  name: hms-app-secret
  namespace: hms-production
type: Opaque
data:
  DB_PASS: cm9vdA==
  JWT_SECRET: c3VwZXJzZWNyZXRrZXlfY2hhbmdlX2luX3Byb2Q=
